### ISSUE TITLE
GoTo Page Behaviour

### ISSUE THREAD

**Issue by samsoft00** [tekinarslan/AndroidPdfViewer#14]
Hello @teckinarslan, great libs, please how can i implement GoTo behavior, i want the user to be able to go to a particular page (Example page 12). Thanks

**Comment by samsoft00** [comment]
@tekinarslan I'm still waiting for your response on this.. if you've any other option, kindly let me know. Thanks

**Comment by tekinarslan** [comment]
Hı, if you modify gotoPage method of muPdfCore class, you can go to specific page.But I dont want to license info for modify any library code.

**Comment by samsoft00** [comment]
@tekinarslan Thanks for your response, i really appreciate... i've implement the logic but its not working... 

```
    public void goToNewPage(){
        ArrayAdapter<String> numPages = new ArrayAdapter<String>(getActivity(),
                android.R.layout.simple_spinner_dropdown_item,
                new String[]{"Page 1", "Page 2", "Page 3"});


        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_LIST);

        ActionBar.OnNavigationListener listener = new ActionBar.OnNavigationListener() {
            @Override
            public boolean onNavigationItemSelected(int i, long l) {
                core.gotoPage(i+1); //not working
                return false;
            }
        };

        actionBar.setListNavigationCallbacks(numPages, listener);
    }

```
Thanks for your help!
