### ISSUE TITLE
Lib is not working for lollipop

### ISSUE THREAD

**Issue by ManojMM026** [tekinarslan/AndroidPdfViewer#9]
Hi whenever I try to add Ink Annotation programmatically I get following error .

03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: illegal class name 'android.graphics.PointF'
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]     (should be of the form 'package/Class', [Lpackage/Class;' or '[[B')
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]     in call to FindClass
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]     from void com.artifex.mupdfdemo.MuPDFCore.addInkAnnotationInternal(android.graphics.PointF[][])
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65] "AsyncTask #1" prio=5 tid=26 Runnable
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12c5dd60 self=0x5f6f2650
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   | sysTid=3513 nice=10 cgrp=apps/bg_non_interactive sched=0/0 handle=0x5f481528
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   | state=R schedstat=( 2350000 11713000 5 ) utm=0 stm=0 core=2 HZ=100
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   | stack=0x6d09a000-0x6d09c000 stackSize=1036KB
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #00 pc 00004ce4  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #01 pc 00003531  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #02 pc 0023fdad  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #03 pc 00224f6f  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+146)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #04 pc 000b0443  /system/lib/libart.so (???)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #05 pc 000b0b7d  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #06 pc 000b4993  /system/lib/libart.so (???)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #07 pc 000252f7  /data/app/com.akillitablet.android-1/lib/arm/libmupdf.so (Java_com_artifex_mupdfdemo_MuPDFCore_addInkAnnotationInternal+358)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   native: #08 pc 000bdbe7  /data/dalvik-cache/arm/data@app@com.akillitablet.android-1@base.apk@classes.dex (Java_com_artifex_mupdfdemo_MuPDFCore_addInkAnnotationInternal___3_3Landroid_graphics_PointF_2+102)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   at com.artifex.mupdfdemo.MuPDFCore.addInkAnnotationInternal(Native method)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   at com.artifex.mupdfdemo.MuPDFCore.addInkAnnotation(MuPDFCore.java:296)
03-01 17:18:12.905: A/art(3257): art/runtime/check_jni.cc:65]   - locked <0x3fce6163> (a com.artifex.mupdfdemo.MuPDFCore)

I did bit of google. End up having answers as its bug in lollipop. Can you please help me with this?

**Comment by tekinarslan** [comment]
I am test lib for Lollipop, but annotation bug maybe for Lollipop. I will update all library with new version, maybe solving.
